# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/alexandre.juca/opensource/C/fkvs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/alexandre.juca/opensource/C/fkvs

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alexandre.juca/opensource/C/fkvs/CMakeFiles /Users/alexandre.juca/opensource/C/fkvs//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alexandre.juca/opensource/C/fkvs/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --blue --bold "Finished generating code"
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fkvs

# Build rule for target.
fkvs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fkvs
.PHONY : fkvs

# fast build rule for target.
fkvs/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fkvs.dir/build.make CMakeFiles/fkvs.dir/build
.PHONY : fkvs/fast

#=============================================================================
# Target rules for targets named fkvs-cli

# Build rule for target.
fkvs-cli: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fkvs-cli
.PHONY : fkvs-cli

# fast build rule for target.
fkvs-cli/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fkvs-cli.dir/build.make CMakeFiles/fkvs-cli.dir/build
.PHONY : fkvs-cli/fast

client_command_handlers.o: client_command_handlers.c.o
.PHONY : client_command_handlers.o

# target to build an object file
client_command_handlers.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fkvs-cli.dir/build.make CMakeFiles/fkvs-cli.dir/client_command_handlers.c.o
.PHONY : client_command_handlers.c.o

client_command_handlers.i: client_command_handlers.c.i
.PHONY : client_command_handlers.i

# target to preprocess a source file
client_command_handlers.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fkvs-cli.dir/build.make CMakeFiles/fkvs-cli.dir/client_command_handlers.c.i
.PHONY : client_command_handlers.c.i

client_command_handlers.s: client_command_handlers.c.s
.PHONY : client_command_handlers.s

# target to generate assembly for a file
client_command_handlers.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fkvs-cli.dir/build.make CMakeFiles/fkvs-cli.dir/client_command_handlers.c.s
.PHONY : client_command_handlers.c.s

command_parser.o: command_parser.c.o
.PHONY : command_parser.o

# target to build an object file
command_parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fkvs-cli.dir/build.make CMakeFiles/fkvs-cli.dir/command_parser.c.o
.PHONY : command_parser.c.o

command_parser.i: command_parser.c.i
.PHONY : command_parser.i

# target to preprocess a source file
command_parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fkvs-cli.dir/build.make CMakeFiles/fkvs-cli.dir/command_parser.c.i
.PHONY : command_parser.c.i

command_parser.s: command_parser.c.s
.PHONY : command_parser.s

# target to generate assembly for a file
command_parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fkvs-cli.dir/build.make CMakeFiles/fkvs-cli.dir/command_parser.c.s
.PHONY : command_parser.c.s

command_registry.o: command_registry.c.o
.PHONY : command_registry.o

# target to build an object file
command_registry.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fkvs.dir/build.make CMakeFiles/fkvs.dir/command_registry.c.o
.PHONY : command_registry.c.o

command_registry.i: command_registry.c.i
.PHONY : command_registry.i

# target to preprocess a source file
command_registry.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fkvs.dir/build.make CMakeFiles/fkvs.dir/command_registry.c.i
.PHONY : command_registry.c.i

command_registry.s: command_registry.c.s
.PHONY : command_registry.s

# target to generate assembly for a file
command_registry.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fkvs.dir/build.make CMakeFiles/fkvs.dir/command_registry.c.s
.PHONY : command_registry.c.s

config.o: config.c.o
.PHONY : config.o

# target to build an object file
config.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fkvs-cli.dir/build.make CMakeFiles/fkvs-cli.dir/config.c.o
.PHONY : config.c.o

config.i: config.c.i
.PHONY : config.i

# target to preprocess a source file
config.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fkvs-cli.dir/build.make CMakeFiles/fkvs-cli.dir/config.c.i
.PHONY : config.c.i

config.s: config.c.s
.PHONY : config.s

# target to generate assembly for a file
config.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fkvs-cli.dir/build.make CMakeFiles/fkvs-cli.dir/config.c.s
.PHONY : config.c.s

event_dispatcher_kqueue.o: event_dispatcher_kqueue.c.o
.PHONY : event_dispatcher_kqueue.o

# target to build an object file
event_dispatcher_kqueue.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fkvs.dir/build.make CMakeFiles/fkvs.dir/event_dispatcher_kqueue.c.o
.PHONY : event_dispatcher_kqueue.c.o

event_dispatcher_kqueue.i: event_dispatcher_kqueue.c.i
.PHONY : event_dispatcher_kqueue.i

# target to preprocess a source file
event_dispatcher_kqueue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fkvs.dir/build.make CMakeFiles/fkvs.dir/event_dispatcher_kqueue.c.i
.PHONY : event_dispatcher_kqueue.c.i

event_dispatcher_kqueue.s: event_dispatcher_kqueue.c.s
.PHONY : event_dispatcher_kqueue.s

# target to generate assembly for a file
event_dispatcher_kqueue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fkvs.dir/build.make CMakeFiles/fkvs.dir/event_dispatcher_kqueue.c.s
.PHONY : event_dispatcher_kqueue.c.s

fkvs-cli.o: fkvs-cli.c.o
.PHONY : fkvs-cli.o

# target to build an object file
fkvs-cli.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fkvs-cli.dir/build.make CMakeFiles/fkvs-cli.dir/fkvs-cli.c.o
.PHONY : fkvs-cli.c.o

fkvs-cli.i: fkvs-cli.c.i
.PHONY : fkvs-cli.i

# target to preprocess a source file
fkvs-cli.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fkvs-cli.dir/build.make CMakeFiles/fkvs-cli.dir/fkvs-cli.c.i
.PHONY : fkvs-cli.c.i

fkvs-cli.s: fkvs-cli.c.s
.PHONY : fkvs-cli.s

# target to generate assembly for a file
fkvs-cli.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fkvs-cli.dir/build.make CMakeFiles/fkvs-cli.dir/fkvs-cli.c.s
.PHONY : fkvs-cli.c.s

hashtable.o: hashtable.c.o
.PHONY : hashtable.o

# target to build an object file
hashtable.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fkvs.dir/build.make CMakeFiles/fkvs.dir/hashtable.c.o
.PHONY : hashtable.c.o

hashtable.i: hashtable.c.i
.PHONY : hashtable.i

# target to preprocess a source file
hashtable.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fkvs.dir/build.make CMakeFiles/fkvs.dir/hashtable.c.i
.PHONY : hashtable.c.i

hashtable.s: hashtable.c.s
.PHONY : hashtable.s

# target to generate assembly for a file
hashtable.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fkvs.dir/build.make CMakeFiles/fkvs.dir/hashtable.c.s
.PHONY : hashtable.c.s

server.o: server.c.o
.PHONY : server.o

# target to build an object file
server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fkvs.dir/build.make CMakeFiles/fkvs.dir/server.c.o
.PHONY : server.c.o

server.i: server.c.i
.PHONY : server.i

# target to preprocess a source file
server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fkvs.dir/build.make CMakeFiles/fkvs.dir/server.c.i
.PHONY : server.c.i

server.s: server.c.s
.PHONY : server.s

# target to generate assembly for a file
server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fkvs.dir/build.make CMakeFiles/fkvs.dir/server.c.s
.PHONY : server.c.s

server_command_handlers.o: server_command_handlers.c.o
.PHONY : server_command_handlers.o

# target to build an object file
server_command_handlers.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fkvs.dir/build.make CMakeFiles/fkvs.dir/server_command_handlers.c.o
.PHONY : server_command_handlers.c.o

server_command_handlers.i: server_command_handlers.c.i
.PHONY : server_command_handlers.i

# target to preprocess a source file
server_command_handlers.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fkvs.dir/build.make CMakeFiles/fkvs.dir/server_command_handlers.c.i
.PHONY : server_command_handlers.c.i

server_command_handlers.s: server_command_handlers.c.s
.PHONY : server_command_handlers.s

# target to generate assembly for a file
server_command_handlers.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fkvs.dir/build.make CMakeFiles/fkvs.dir/server_command_handlers.c.s
.PHONY : server_command_handlers.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... fkvs"
	@echo "... fkvs-cli"
	@echo "... client_command_handlers.o"
	@echo "... client_command_handlers.i"
	@echo "... client_command_handlers.s"
	@echo "... command_parser.o"
	@echo "... command_parser.i"
	@echo "... command_parser.s"
	@echo "... command_registry.o"
	@echo "... command_registry.i"
	@echo "... command_registry.s"
	@echo "... config.o"
	@echo "... config.i"
	@echo "... config.s"
	@echo "... event_dispatcher_kqueue.o"
	@echo "... event_dispatcher_kqueue.i"
	@echo "... event_dispatcher_kqueue.s"
	@echo "... fkvs-cli.o"
	@echo "... fkvs-cli.i"
	@echo "... fkvs-cli.s"
	@echo "... hashtable.o"
	@echo "... hashtable.i"
	@echo "... hashtable.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
	@echo "... server_command_handlers.o"
	@echo "... server_command_handlers.i"
	@echo "... server_command_handlers.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

