# Custom Makefile to setup and build fkvs

.PHONY: setup build setup-and-build tests

setup:
	cd deps/linenoise && git submodule init && git submodule update && cd ../../

build:
	cmake . && cmake --build .

setup-and-build: setup build

tests: setup-and-build
	ctest --output-on-failure

codesign-server: setup-and-build
	codesign --entitlements entitlements.plist --force --sign - ./fkvs-server