# Custom Makefile to setup and build fkvs

.PHONY: setup build setup-and-build

setup:
	cd deps/linenoise && git submodule init && git submodule update && cd ../../

build:
	cmake . && cmake --build .

setup-and-build: setup build